FROM rust:latest as builder

# Install build dependencies
RUN apt-get update && apt-get install -y cmake clang pkg-config && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/bare-metal-canvas
# Copy workspace config
COPY Cargo.toml Cargo.lock* ./

# Copy packages
COPY server ./server
COPY client ./client

# Build client
RUN cargo build --release -p client

FROM debian:bookworm-slim

COPY --from=builder /usr/src/bare-metal-canvas/target/release/client /loadgen
RUN chmod +x /loadgen

WORKDIR /
